[project]
name = "ecs-api-deploy-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi==0.116.1",
    "pydantic>=2,<3",
    "uvicorn==0.35.0",
]
