version: 3
tasks:
  terraform-init:
    desc: Initialize Terraform.
    dir: infrastructure
    sources:
      - "**/main.tf"
    cmds:
      - cd ecr && terraform init && cd ..
      - cd service && terraform init && cd ..

  deploy-ecr:
    desc: Deploy the ECR to store docker images.
    dir: infrastructure/ecr
    deps:
      - terraform-init
    cmds:
      - terraform validate
      - terraform apply -auto-approve -input=false

  deploy-service:
    desc: Deploy the service to ECS.
    dir: infrastructure/ecr
    deps:
      - terraform-init
    cmds:
      - terraform validate
      - terraform apply -auto-approve -input=false

  deploy:
    desc: Deploy the function to AWS.
    dir: infrastructure
    deps:
      - terraform-init
    cmds:
      - task: deploy-ecr
      - task: deploy-service

  take-down:
    desc: Take down the infrastructure from AWS.
    dir: infrastructure
    cmds:
      - cd ecr && terraform destroy -auto-approve -input=false && cd ..
      - cd service && terraform destroy -auto-approve -input=false && cd ..
