version: 3
tasks:
  terraform-init:
    desc: Initialize Terraform.
    dir: infrastructure
    sources:
      - "**/main.tf"
    cmds:
      - cd ecr && terraform init && cd ..
      - cd service && terraform init && cd ..

  deploy-ecr:
    desc: Deploy the ECR to store docker images.
    dir: infrastructure/ecr
    deps:
      - terraform-init
    cmds:
      - terraform validate
      - terraform apply -auto-approve -input=false

  deploy-service:
    desc: Deploy the service to ECS.
    dir: infrastructure/service
    deps:
      - terraform-init
    cmds:
      - terraform validate
      - terraform apply -auto-approve -input=false

  deploy:
    desc: Deploy the function to AWS.
    dir: infrastructure
    deps:
      - terraform-init
    cmds:
      - task: deploy-ecr
      - task: deploy-service

  take-down:
    desc: Take down the infrastructure from AWS.
    dir: infrastructure
    cmds:
      - cd ecr && terraform destroy -auto-approve -input=false && cd ..
      - cd service && terraform destroy -auto-approve -input=false && cd ..

  load-img-to-ecr:
    dotenv:
      - ".env"
    cmds:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_URI
      - docker build -t ecs-api-test-repository .
      - docker tag ecs-api-test-repository:latest $ECR_URI/ecs-api-test-repository:latest
      - docker push $ECR_URI/ecs-api-test-repository:latest
